import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ja' | 'ko' | 'zh' | 'ar' | 'ru' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    trending: 'Trending',
    recommended: 'Recommended',
    premium: 'Premium',
    categories: 'Categories',
    search: 'Search',
    login: 'Login',
    logout: 'Log Out',
    profile: 'Profile',
    settings: 'Settings',
    upload: 'Upload',
    notifications: 'Notifications',
    inbox: 'Inbox',
    favorites: 'Favorites',
    liked_videos: 'Liked Videos',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    contact: 'Contact Us',
    language: 'Language',
    see_profile: 'See Your Profile',
    edit_profile: 'Edit Profile',
    share: 'Share',
    about: 'About',
    videos: 'Videos',
    photos: 'Photos',
    stream: 'Stream',
    more: 'More',
  },
  es: {
    home: 'Inicio',
    trending: 'Tendencias',
    recommended: 'Recomendado',
    premium: 'Premium',
    categories: 'Categorías',
    search: 'Buscar',
    login: 'Iniciar Sesión',
    logout: 'Cerrar Sesión',
    profile: 'Perfil',
    settings: 'Configuración',
    upload: 'Subir',
    notifications: 'Notificaciones',
    inbox: 'Bandeja de entrada',
    favorites: 'Favoritos',
    liked_videos: 'Videos que Me Gustan',
    terms: 'Términos de Servicio',
    privacy: 'Política de Privacidad',
    contact: 'Contáctanos',
    language: 'Idioma',
    see_profile: 'Ver Tu Perfil',
    edit_profile: 'Editar Perfil',
    share: 'Compartir',
    about: 'Acerca de',
    videos: 'Videos',
    photos: 'Fotos',
    stream: 'Stream',
    more: 'Más',
  },
  fr: {
    home: 'Accueil',
    trending: 'Tendances',
    recommended: 'Recommandé',
    premium: 'Premium',
    categories: 'Catégories',
    search: 'Rechercher',
    login: 'Se connecter',
    logout: 'Se déconnecter',
    profile: 'Profil',
    settings: 'Paramètres',
    upload: 'Télécharger',
    notifications: 'Notifications',
    inbox: 'Boîte de réception',
    favorites: 'Favoris',
    liked_videos: 'Vidéos aimées',
    terms: 'Conditions de service',
    privacy: 'Politique de confidentialité',
    contact: 'Nous contacter',
    language: 'Langue',
    see_profile: 'Voir votre profil',
    edit_profile: 'Modifier le profil',
    share: 'Partager',
    about: 'À propos',
    videos: 'Vidéos',
    photos: 'Photos',
    stream: 'Stream',
    more: 'Plus',
  },
  de: {
    home: 'Startseite',
    trending: 'Im Trend',
    recommended: 'Empfohlen',
    premium: 'Premium',
    categories: 'Kategorien',
    search: 'Suchen',
    login: 'Anmelden',
    logout: 'Abmelden',
    profile: 'Profil',
    settings: 'Einstellungen',
    upload: 'Hochladen',
    notifications: 'Benachrichtigungen',
    inbox: 'Posteingang',
    favorites: 'Favoriten',
    liked_videos: 'Gelikte Videos',
    terms: 'Nutzungsbedingungen',
    privacy: 'Datenschutz',
    contact: 'Kontakt',
    language: 'Sprache',
    see_profile: 'Dein Profil ansehen',
    edit_profile: 'Profil bearbeiten',
    share: 'Teilen',
    about: 'Über',
    videos: 'Videos',
    photos: 'Fotos',
    stream: 'Stream',
    more: 'Mehr',
  },
  it: {
    home: 'Casa',
    trending: 'Di tendenza',
    recommended: 'Consigliato',
    premium: 'Premium',
    categories: 'Categorie',
    search: 'Cerca',
    login: 'Accedi',
    logout: 'Disconnetti',
    profile: 'Profilo',
    settings: 'Impostazioni',
    upload: 'Carica',
    notifications: 'Notifiche',
    inbox: 'Posta in arrivo',
    favorites: 'Preferiti',
    liked_videos: 'Video piaciuti',
    terms: 'Termini di servizio',
    privacy: 'Privacy',
    contact: 'Contattaci',
    language: 'Lingua',
    see_profile: 'Vedi il tuo profilo',
    edit_profile: 'Modifica profilo',
    share: 'Condividi',
    about: 'Informazioni',
    videos: 'Video',
    photos: 'Foto',
    stream: 'Stream',
    more: 'Altro',
  },
  pt: {
    home: 'Início',
    trending: 'Em alta',
    recommended: 'Recomendado',
    premium: 'Premium',
    categories: 'Categorias',
    search: 'Pesquisar',
    login: 'Entrar',
    logout: 'Sair',
    profile: 'Perfil',
    settings: 'Configurações',
    upload: 'Upload',
    notifications: 'Notificações',
    inbox: 'Caixa de entrada',
    favorites: 'Favoritos',
    liked_videos: 'Vídeos curtidos',
    terms: 'Termos de serviço',
    privacy: 'Política de privacidade',
    contact: 'Contate-nos',
    language: 'Idioma',
    see_profile: 'Ver seu perfil',
    edit_profile: 'Editar perfil',
    share: 'Compartilhar',
    about: 'Sobre',
    videos: 'Vídeos',
    photos: 'Fotos',
    stream: 'Stream',
    more: 'Mais',
  },
  ja: {
    home: 'ホーム',
    trending: 'トレンド',
    recommended: 'おすすめ',
    premium: 'プレミアム',
    categories: 'カテゴリー',
    search: '検索',
    login: 'ログイン',
    logout: 'ログアウト',
    profile: 'プロフィール',
    settings: '設定',
    upload: 'アップロード',
    notifications: '通知',
    inbox: '受信箱',
    favorites: 'お気に入り',
    liked_videos: 'いいね！した動画',
    terms: '利用規約',
    privacy: 'プライバシーポリシー',
    contact: 'お問い合わせ',
    language: '言語',
    see_profile: 'プロフィールを見る',
    edit_profile: 'プロフィール編集',
    share: '共有',
    about: '概要',
    videos: '動画',
    photos: '写真',
    stream: 'ストリーム',
    more: 'その他',
  },
  ko: {
    home: '홈',
    trending: '인기',
    recommended: '추천',
    premium: '프리미엄',
    categories: '카테고리',
    search: '검색',
    login: '로그인',
    logout: '로그아웃',
    profile: '프로필',
    settings: '설정',
    upload: '업로드',
    notifications: '알림',
    inbox: '받은편지함',
    favorites: '즐겨찾기',
    liked_videos: '좋아요 표시한 동영상',
    terms: '서비스 약관',
    privacy: '개인정보 처리방침',
    contact: '문의하기',
    language: '언어',
    see_profile: '프로필 보기',
    edit_profile: '프로필 수정',
    share: '공유',
    about: '정보',
    videos: '동영상',
    photos: '사진',
    stream: '스트림',
    more: '더보기',
  },
  zh: {
    home: '首页',
    trending: '热门',
    recommended: '推荐',
    premium: '高级',
    categories: '分类',
    search: '搜索',
    login: '登录',
    logout: '退出',
    profile: '个人资料',
    settings: '设置',
    upload: '上传',
    notifications: '通知',
    inbox: '收件箱',
    favorites: '收藏夹',
    liked_videos: '点赞的视频',
    terms: '服务条款',
    privacy: '隐私政策',
    contact: '联系我们',
    language: '语言',
    see_profile: '查看您的个人资料',
    edit_profile: '编辑个人资料',
    share: '分享',
    about: '关于',
    videos: '视频',
    photos: '照片',
    stream: '直播',
    more: '更多',
  },
  ar: {
    home: 'الرئيسية',
    trending: 'الرائج',
    recommended: 'مُوصى به',
    premium: 'بريميوم',
    categories: 'الفئات',
    search: 'بحث',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    upload: 'رفع',
    notifications: 'الإشعارات',
    inbox: 'البريد الوارد',
    favorites: 'المفضلة',
    liked_videos: 'الفيديوهات المعجب بها',
    terms: 'شروط الخدمة',
    privacy: 'سياسة الخصوصية',
    contact: 'اتصل بنا',
    language: 'اللغة',
    see_profile: 'عرض ملفك الشخصي',
    edit_profile: 'تحرير الملف الشخصي',
    share: 'مشاركة',
    about: 'حول',
    videos: 'فيديوهات',
    photos: 'صور',
    stream: 'بث مباشر',
    more: 'المزيد',
  },
  ru: {
    home: 'Главная',
    trending: 'В тренде',
    recommended: 'Рекомендуемое',
    premium: 'Премиум',
    categories: 'Категории',
    search: 'Поиск',
    login: 'Войти',
    logout: 'Выйти',
    profile: 'Профиль',
    settings: 'Настройки',
    upload: 'Загрузить',
    notifications: 'Уведомления',
    inbox: 'Входящие',
    favorites: 'Избранное',
    liked_videos: 'Понравившиеся видео',
    terms: 'Условия обслуживания',
    privacy: 'Политика конфиденциальности',
    contact: 'Связаться с нами',
    language: 'Язык',
    see_profile: 'Посмотреть ваш профиль',
    edit_profile: 'Редактировать профиль',
    share: 'Поделиться',
    about: 'О нас',
    videos: 'Видео',
    photos: 'Фото',
    stream: 'Стрим',
    more: 'Еще',
  },
  hi: {
    home: 'होम',
    trending: 'ट्रेंडिंग',
    recommended: 'सुझाया गया',
    premium: 'प्रीमियम',
    categories: 'श्रेणियां',
    search: 'खोजें',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    upload: 'अपलोड',
    notifications: 'सूचनाएं',
    inbox: 'इनबॉक्स',
    favorites: 'पसंदीदा',
    liked_videos: 'पसंद किए गए वीडियो',
    terms: 'सेवा की शर्तें',
    privacy: 'गोपनीयता नीति',
    contact: 'संपर्क करें',
    language: 'भाषा',
    see_profile: 'अपनी प्रोफाइल देखें',
    edit_profile: 'प्रोफाइल संपादित करें',
    share: 'साझा करें',
    about: 'के बारे में',
    videos: 'वीडियो',
    photos: 'फोटो',
    stream: 'स्ट्रीम',
    more: 'और',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  ja: '日本語',
  ko: '한국어',
  zh: '中文',
  ar: 'العربية',
  ru: 'Русский',
  hi: 'हिन्दी',
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { languageNames };
export type { Language };