// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhahzghkbbiujxjhunob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoYWh6Z2hrYmJpdWp4amh1bm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjc0OTAsImV4cCI6MjA2NjcwMzQ5MH0.ez7AZCz4HQ_GJremQB3-XrWQwqldKeHkSWPxzEZRbWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.sessionStorage, // This will clear session when browser closes
    autoRefreshToken: true,
    persistSession: true
  }
});