// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbfmaoncafjtvpgrypsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiZm1hb25jYWZqdHZwZ3J5cHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTgxNjcsImV4cCI6MjA2NjY5NDE2N30.04mssmOumexeTKU3hhmFQSfLIe-q3YIDnjrp5UrJh9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);